### ISSUE TITLE
Force calculated multiple times?

### ISSUE THREAD

**Issue by sjcrs** [zhanghe9704/electroncooling#5]
https://github.com/zhanghe9704/electroncooling/blob/9d5d8e68150c9b3aaf9849aa0802feaae056dab9/src/ecooling.cc#L1008-L1016

It appears there's a case where force is called three times between transition to the beam frame and transition back to the lab frame, since force() is called within bunched_to_coasting. Is this intended, or should the force call at line 1008 be the start of an if/else statement?

**Comment by zhanghe9704** [comment]
This is intended. A few years ago, we consider using a bunched electron beam to cool a coasting ion beam. The coasting ion beam is model only on a crosssection, assuming it's the same everywhere. However, the bunched electron beam density/temperature could vary along the longitudinal direction. To model the cooling process, we put the coasting ion beam crosssection at the different longitudinal position to the electron beam, calculate the friction force and take the average. BTW, this feature hasn't been used for a long time, since we do NOT to this bunched-to-coasting cooling now.
